// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZHmHaTxW9AMBknyWugt8Q1MU8mwX_WWk',
    appId: '1:535553892535:web:095bc5c4d1b6b1397b6d32',
    messagingSenderId: '535553892535',
    projectId: 'lansonndehplumbing',
    authDomain: 'lansonndehplumbing.firebaseapp.com',
    storageBucket: 'lansonndehplumbing.appspot.com',
    measurementId: 'G-T0L731HGPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB13oR_IeDFHf9uz0A6-vUECduSbNr-uM8',
    appId: '1:535553892535:android:ff99a8a30c57911c7b6d32',
    messagingSenderId: '535553892535',
    projectId: 'lansonndehplumbing',
    storageBucket: 'lansonndehplumbing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFNlRobdLQWUUezlSC4N2hPjyORWCzh9Q',
    appId: '1:535553892535:ios:00561913bfc6bb547b6d32',
    messagingSenderId: '535553892535',
    projectId: 'lansonndehplumbing',
    storageBucket: 'lansonndehplumbing.appspot.com',
    iosClientId: '535553892535-k560fnjhdm57m5p4uhsdvh1ms7vlu70f.apps.googleusercontent.com',
    iosBundleId: 'com.lansonndeh.lansonndehplumbing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFNlRobdLQWUUezlSC4N2hPjyORWCzh9Q',
    appId: '1:535553892535:ios:12053591be62da237b6d32',
    messagingSenderId: '535553892535',
    projectId: 'lansonndehplumbing',
    storageBucket: 'lansonndehplumbing.appspot.com',
    iosClientId: '535553892535-o2pqtaj9r81nghchosr9bbslaeldk16v.apps.googleusercontent.com',
    iosBundleId: 'com.lansonndeh.lansonndehplumbing.RunnerTests',
  );
}
